### ISSUE TITLE
MacOS web midi support

### ISSUE THREAD

**Issue by ilesinge** [emprcl/signls#2]
While trying to launch signls on MacOS, It closes automatically with the following message "no midi drivers" even though I have Enfer opened with webmidi permissions given.

**Comment by xaviergodart** [comment]
Weird, it should be handled by rtmidi.
What's your macOS version and browser?

**Comment by xaviergodart** [comment]
Could you try this build as well? 
[signls_80cb6947fe2f40a917e64a56cb02c4a35180c505_macOS.zip](https://github.com/user-attachments/files/17577352/signls_80cb6947fe2f40a917e64a56cb02c4a35180c505_macOS.zip)

It exposes a default virtual midi output (RtMidi Output Client: default) that you should be able to see and connect in your midi setup configuration (https://support.apple.com/guide/audio-midi-setup/set-up-midi-devices-ams875bae1e0/mac).

**Comment by xaviergodart** [comment]
It turns out that Enfer force the use of a specific midi device that does not exist on macos. Everything should be working fine with other webmidi synths.

Closing this for now, but feel free to reopen if needed.
