### ISSUE TITLE
Add MIDI CC messages

### ISSUE THREAD

**Issue by xaviergodart** [emprcl/signls#3]
Signls should be capable of **MIDI CCs** as well.

We could add that in 2 ways:
 1. each node can either send a midi note or a midi cc. It seems like it's the most comprehensible way to integrate that, and it follow the one-message-per-node philosophy. But I can see it could be challenging in some cases to send a note and a cc at the same time. The Zone node would be very useful in that case, but I'm unsure it would cover all use cases.
 2. each node can send a number of midi ccs alongside the note. It would be more flexible, but also more complicated from a UI/UX perspective (need to add additional parameters to nodes) and I would make each grid less readable because one node can do multiple things.

I have a preference for the solution 1, but would gladly take feedback on that.

**Comment by jsmcnair** [comment]
I don't think I understand how it works enough to know how limiting 1. would be, but it sounds like it would be a good place to start. For 2. maybe there could be some kind of editable table that maps CC# to values?

**Comment by xaviergodart** [comment]
For the option 2, the question is more _where_ in the interface we should add the new parameters.
One way would be to add **parameter pages**.

When you edit a node, the first page would display parameters you see right now.
With new keybindings (or old ones now I think about it, `up` and `down` aren't used in parameters without `ctrl`, so we could used them), we could display new pages of parameters:
 - first page: midi note and node parameters
 - second page: midi CCs
 - third page: [meta commands](https://github.com/emprcl/signls/issues/4)
 
I think I could see that working. It might even be easier to explain than the option 1 where there's specific node types (note nodes, cc nodes and meta nodes).

**Comment by xaviergodart** [comment]
**MIDI CCs** available in [v0.4.0](https://github.com/emprcl/signls/releases/tag/v0.4.0).

User manual will be updated asap.
